return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPre", "BufNewFile" },
	build = ":TSUpdate",
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		local treesitter = require("nvim-treesitter.configs")

		treesitter.setup({
			highlight = { enable = true },
			indent = { enable = true },
			autotag = { enable = true },
			auto_install = true,
			ensure_installed = {
				"asm",
				"astro",
				"bash",
				"c",
				"cmake",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"dot",
				"editorconfig",
				"elixir",
				"erlang",
				"gleam",
				"glsl",
				"go",
				"heex",
				"helm",
				"html",
				"http",
				"javascript",
				"json",
				"lua",
				"make",
				"nix",
				"proto",
				"python",
				"regex",
				"rescript",
				"robots",
				"ruby",
				"rust",
				"sql",
				"toml",
				"typescript",
				"vim",
				"xml",
				"yaml",
				"zig",
			},
		})
	end,
}
